# Generated by Django 5.2.5 on 2025-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="e.g., Mortgages, Life Insurance, Property Insurance",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["email"], name="idx_advisor_email"),
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["license_number"], name="idx_advisor_license"),
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["active"], name="idx_advisor_active"),
        ),
    ]
