# Generated by Django 5.2.5 on 2025-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_customer_advisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="insurance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Life Insurance", "Life Insurance"),
                    ("Critical Illness", "Critical Illness"),
                    ("Income Protection", "Income Protection"),
                    ("Buildings Insurance", "Buildings Insurance"),
                    ("Contents Insurance", "Contents Insurance"),
                    ("Motor Insurance", "Motor Insurance"),
                    ("Travel Insurance", "Travel Insurance"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
