# Generated by Django 5.2.5 on 2025-08-25 08:49

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_application_insurance_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancepolicy",
            name="insurance_id",
            field=models.CharField(
                default=crm.models.generate_insurance_id,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="mortgage",
            name="mortgage_id",
            field=models.CharField(
                default=crm.models.generate_insurance_id,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
