# Generated by Django 5.2.5 on 2025-08-28 18:29

import crm.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mortgages, Life Insurance, Property Insurance",
                        max_length=100,
                    ),
                ),
                ("hire_date", models.DateField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_manager", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "advisor",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "solicitor_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("Mortgage", "Mortgage"),
                            ("Insurance", "Insurance"),
                            ("Both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("application_number", models.CharField(max_length=50, unique=True)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("Initial Contact", "Initial Contact"),
                            ("Documents Requested", "Documents Requested"),
                            ("Documents Received", "Documents Received"),
                            ("Application Submitted", "Application Submitted"),
                            ("Under Review", "Under Review"),
                            ("Underwriting", "Underwriting"),
                            ("Additional Info Required", "Additional Info Required"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                            ("Withdrawn", "Withdrawn"),
                            ("Completed", "Completed"),
                        ],
                        default="Initial Contact",
                        max_length=30,
                    ),
                ),
                (
                    "application_priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("documents_checklist", models.JSONField(blank=True, default=dict)),
                ("advisor_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "client_communication_log",
                    models.JSONField(blank=True, default=list),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurance_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Life Insurance", "Life Insurance"),
                            ("Critical Illness", "Critical Illness"),
                            ("Income Protection", "Income Protection"),
                            ("Buildings Insurance", "Buildings Insurance"),
                            ("Contents Insurance", "Contents Insurance"),
                            ("Motor Insurance", "Motor Insurance"),
                            ("Travel Insurance", "Travel Insurance"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="CommissionWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Pending Review", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Paid", "Paid"),
                            ("Disputed", "Disputed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                (
                    "total_estimated_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_actual_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week_number"],
            },
        ),
        migrations.CreateModel(
            name="CommissionApplicationMapping",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estimated_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commission_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.commissionweek",
                    ),
                ),
            ],
            options={
                "db_table": "commission_application_mappings",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("Employed", "Employed"),
                            ("Self-Employed", "Self-Employed"),
                            ("Unemployed", "Unemployed"),
                            ("Retired", "Retired"),
                            ("Student", "Student"),
                        ],
                        default="Employed",
                        max_length=20,
                    ),
                ),
                ("employer", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dependents", models.IntegerField(default=0)),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Referral, Website, Advertisement",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "communication_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("Phone Call", "Phone Call"),
                            ("Email", "Email"),
                            ("SMS", "SMS"),
                            ("Meeting", "Meeting"),
                            ("Letter", "Letter"),
                            ("Video Call", "Video Call"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("Inbound", "Inbound"), ("Outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=200)),
                ("follow_up_required", models.BooleanField(default=0)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("communication_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.application",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
            ],
            options={
                "db_table": "communications",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID Proof", "ID Proof"),
                            ("Address Proof", "Address Proof"),
                            ("Income Proof", "Income Proof"),
                            ("Bank Statement", "Bank Statement"),
                            ("Credit Report", "Credit Report"),
                            ("Property Valuation", "Property Valuation"),
                            ("Insurance Medical", "Insurance Medical"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("Required", "Required"),
                            ("Requested", "Requested"),
                            ("Received", "Received"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Required",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "insurance_id",
                    models.CharField(
                        default=crm.models.generate_insurance_id,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("Life Insurance", "Life Insurance"),
                            ("Critical Illness", "Critical Illness"),
                            ("Income Protection", "Income Protection"),
                            ("Buildings Insurance", "Buildings Insurance"),
                            ("Contents Insurance", "Contents Insurance"),
                            ("Motor Insurance", "Motor Insurance"),
                            ("Travel Insurance", "Travel Insurance"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "premium_frequency",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Semi-Annual", "Semi-Annual"),
                            ("Annual", "Annual"),
                        ],
                        default="Monthly",
                        max_length=20,
                    ),
                ),
                ("insurance_company", models.CharField(max_length=100)),
                ("policy_start_date", models.DateField()),
                ("policy_end_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "policy_status",
                    models.CharField(
                        choices=[
                            ("Quote", "Quote"),
                            ("Active", "Active"),
                            ("Lapsed", "Lapsed"),
                            ("Cancelled", "Cancelled"),
                            ("Claim Pending", "Claim Pending"),
                            ("Renewed", "Renewed"),
                        ],
                        default="Quote",
                        max_length=20,
                    ),
                ),
                (
                    "underwriting_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Standard, Preferred, Super Preferred",
                        max_length=50,
                    ),
                ),
                ("beneficiary", models.CharField(blank=True, max_length=100)),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Commission percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("automatic_renewal", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
            ],
            options={
                "db_table": "insurance_policies",
            },
        ),
        migrations.CreateModel(
            name="CommissionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "estimated_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "actual_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commission_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="crm.commissionweek",
                    ),
                ),
                (
                    "insurance_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.insurancepolicy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.insurancepolicy",
            ),
        ),
        migrations.CreateModel(
            name="Mortgage",
            fields=[
                (
                    "mortgage_id",
                    models.CharField(
                        default=crm.models.generate_insurance_id,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_address", models.TextField()),
                ("property_city", models.CharField(blank=True, max_length=50)),
                ("property_state", models.CharField(blank=True, max_length=50)),
                ("property_postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "property_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="e.g., 3.750 for 3.75%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "loan_term",
                    models.IntegerField(
                        blank=True, help_text="Loan term in years", null=True
                    ),
                ),
                (
                    "mortgage_type",
                    models.CharField(
                        choices=[
                            ("Fixed Rate", "Fixed Rate"),
                            ("Variable Rate", "Variable Rate"),
                            ("Interest Only", "Interest Only"),
                            ("Buy-to-Let", "Buy-to-Let"),
                            ("Remortgage", "Remortgage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lender", models.CharField(blank=True, max_length=100)),
                (
                    "loan_to_value_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="LTV percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("House", "House"),
                            ("Flat", "Flat"),
                            ("Bungalow", "Bungalow"),
                            ("Terraced", "Terraced"),
                            ("Semi-Detached", "Semi-Detached"),
                            ("Detached", "Detached"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Purchase", "Purchase"),
                            ("Remortgage", "Remortgage"),
                            ("Buy-to-Let", "Buy-to-Let"),
                            ("Self-Build", "Self-Build"),
                        ],
                        default="Purchase",
                        max_length=20,
                    ),
                ),
                (
                    "mortgage_status",
                    models.CharField(
                        choices=[
                            ("Enquiry", "Enquiry"),
                            ("Application", "Application"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                            ("Declined", "Declined"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        default="Enquiry",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "broker_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
            ],
            options={
                "db_table": "mortgage",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                ("commission_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("Mortgage", "Mortgage"),
                            ("Insurance", "Insurance"),
                            ("Renewal", "Renewal"),
                            ("Referral", "Referral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Clawed Back", "Clawed Back"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("tax_year", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commission_week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.commissionweek",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.insurancepolicy",
                    ),
                ),
                (
                    "mortgage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.mortgage",
                    ),
                ),
            ],
            options={
                "db_table": "commissions",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="mortgage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.mortgage",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Cheque", "Cheque"),
                            ("Direct Debit", "Direct Debit"),
                            ("Standing Order", "Standing Order"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.insurancepolicy",
                    ),
                ),
                (
                    "mortgage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.mortgage",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["email"], name="idx_advisor_email"),
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["license_number"], name="idx_advisor_license"),
        ),
        migrations.AddIndex(
            model_name="advisor",
            index=models.Index(fields=["active"], name="idx_advisor_active"),
        ),
        migrations.AlterUniqueTogether(
            name="commissionweek",
            unique_together={("advisor", "week_number", "year")},
        ),
        migrations.AddIndex(
            model_name="commissionapplicationmapping",
            index=models.Index(
                fields=["application"], name="commission__applica_42eb6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionapplicationmapping",
            index=models.Index(
                fields=["commission_week"], name="commission__commiss_578ee7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commissionapplicationmapping",
            unique_together={("application", "commission_week")},
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customer_email_c21aac_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["advisor"], name="customer_advisor_a3a680_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"], name="customer_last_na_c66c2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["customer"], name="communicati_custome_5f91fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["advisor"], name="communicati_advisor_0a12e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["communication_date"], name="communicati_communi_7b061f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(
                fields=["follow_up_date"], name="communicati_follow__8eb8a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["application"], name="documents_applica_2654b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["customer"], name="documents_custome_a3fabb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_documen_fc21d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_status"], name="documents_documen_b5d837_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["customer"], name="insurance_p_custome_695e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["advisor"], name="insurance_p_advisor_e05793_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["policy_number"], name="insurance_p_policy__67856c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["policy_type"], name="insurance_p_policy__2fb601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["insurance_company"], name="insurance_p_insuran_6ca613_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["policy_status"], name="insurance_p_policy__bd3e6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepolicy",
            index=models.Index(
                fields=["renewal_date"], name="insurance_p_renewal_6573d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commissionmapping",
            unique_together={("application", "insurance_policy")},
        ),
        migrations.AddIndex(
            model_name="mortgage",
            index=models.Index(fields=["customer"], name="mortgage_custome_dadecc_idx"),
        ),
        migrations.AddIndex(
            model_name="mortgage",
            index=models.Index(fields=["advisor"], name="mortgage_advisor_ea61b6_idx"),
        ),
        migrations.AddIndex(
            model_name="mortgage",
            index=models.Index(
                fields=["mortgage_status"], name="mortgage_mortgag_d9497b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mortgage",
            index=models.Index(fields=["lender"], name="mortgage_lender_577ef9_idx"),
        ),
        migrations.AddIndex(
            model_name="mortgage",
            index=models.Index(
                fields=["mortgage_type"], name="mortgage_mortgag_1e71d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["advisor"], name="commissions_advisor_62e317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["customer"], name="commissions_custome_940c18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["commission_type"], name="commissions_commiss_877dc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["payment_status"], name="commissions_payment_90e005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["tax_year"], name="commissions_tax_yea_60fb33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["customer"], name="application_custome_51b6ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["advisor"], name="application_advisor_d72818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["application_status"], name="application_applica_205bae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["application_type"], name="application_applica_23c812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["follow_up_date"], name="application_follow__c54ca8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["submitted_date"], name="application_submitt_6864d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["customer"], name="payments_custome_8fefc3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["application"], name="payments_applica_2d5ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_status"], name="payments_payment_bbdde9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="payments_payment_aebcb7_idx"
            ),
        ),
    ]
