# Generated by Django 5.2.5 on 2025-08-24 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_advisor_date_of_birth_alter_advisor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="advisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
