# Generated by Django 5.2.5 on 2025-08-28 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_commissionweek_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commissionmapping",
            unique_together={("commission_week", "insurance_policy")},
        ),
        migrations.AlterField(
            model_name="commissionmapping",
            name="insurance_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.insurancepolicy"
            ),
        ),
        migrations.DeleteModel(
            name="CommissionApplicationMapping",
        ),
        migrations.RemoveField(
            model_name="commissionmapping",
            name="application",
        ),
    ]
