# Generated by Django 5.2.5 on 2025-08-29 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_commissionmapping_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raised_date", models.DateTimeField(auto_now_add=True)),
                ("dispute_reason", models.TextField()),
                (
                    "disputed_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "proposed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Review", "In Review"),
                            ("Resolved", "Resolved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="crm.commissionmapping",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-raised_date"],
            },
        ),
    ]
