# Generated by Django 5.2.5 on 2025-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_commissiondispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionmapping",
            name="has_dispute",
            field=models.BooleanField(default=False),
        ),
    ]
