# Generated by Django 5.2.5 on 2025-08-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_insurancepolicy_insurance_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancepolicy",
            name="policy_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
