# Generated by Django 5.2.5 on 2025-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_commissionmapping_has_dispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionmapping",
            name="processing_date",
            field=models.DateField(
                blank=True, help_text="Date when the policy was processed", null=True
            ),
        ),
    ]
