# Generated by Django 5.2.5 on 2025-08-30 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_commissionmapping_processing_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAdvisorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("calls_made", models.PositiveIntegerField(default=0)),
                ("appointments_booked", models.PositiveIntegerField(default=0)),
                ("appointments_attended", models.PositiveIntegerField(default=0)),
                ("presentations_made", models.PositiveIntegerField(default=0)),
                ("references_collected", models.PositiveIntegerField(default=0)),
                ("brochures_sent", models.PositiveIntegerField(default=0)),
                ("brochures_received", models.PositiveIntegerField(default=0)),
                ("customer_introductions", models.PositiveIntegerField(default=0)),
                ("other_sources", models.PositiveIntegerField(default=0)),
                ("policies_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("home_insurance", models.PositiveIntegerField(default=0)),
                ("pending_policies_count", models.PositiveIntegerField(default=0)),
                (
                    "pending_policies_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("remarks", models.TextField(blank=True)),
                ("mortgages", models.PositiveIntegerField(default=0)),
                ("wills", models.PositiveIntegerField(default=0)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily advisor activities",
                "unique_together": {("advisor", "date")},
            },
        ),
        migrations.CreateModel(
            name="PolicySaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("contact_no", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("provider", models.CharField(max_length=255)),
                (
                    "life_cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("policy_number", models.CharField(max_length=100)),
                (
                    "illustration_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "illustration_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "new_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "new_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("policy_status", models.CharField(default="Active", max_length=50)),
                (
                    "cic_cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cic_provider", models.CharField(blank=True, max_length=255)),
                ("cic_policy_number", models.CharField(blank=True, max_length=100)),
                (
                    "cic_illustration_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cic_illustration_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cic_new_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cic_new_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cic_policy_status", models.CharField(blank=True, max_length=50)),
                (
                    "ip_cover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("ip_provider", models.CharField(blank=True, max_length=255)),
                ("ip_policy_number", models.CharField(blank=True, max_length=100)),
                (
                    "ip_illustration_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ip_illustration_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ip_new_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ip_new_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ip_policy_status", models.CharField(blank=True, max_length=50)),
                (
                    "accident_policy_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("accident_units", models.PositiveIntegerField(default=0)),
                (
                    "accident_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_details",
                        to="crm.dailyadvisoractivity",
                    ),
                ),
            ],
        ),
    ]
