# Generated by Django 5.2.5 on 2025-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_insurancepolicy_policy_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advisor",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
