# Generated by Django 5.2.5 on 2025-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_advisor_is_manager_advisor_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
