# Generated by Django 5.2.5 on 2025-08-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_dailyadvisoractivity_policysaledetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.insurancepolicy",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="mortgage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.mortgage",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.insurancepolicy",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="mortgage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.mortgage",
            ),
        ),
    ]
