# Generated by Django 5.2.5 on 2025-08-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_communication_insurance_communication_mortgage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.AddField(
            model_name="document",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="insurance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="crm.insurancepolicy",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.application",
            ),
        ),
    ]
