# Generated by Django 4.2.23 on 2025-08-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_advisor_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionWeek",
            fields=[
                ("week_id", models.AutoField(primary_key=True, serialize=False)),
                ("week_number", models.IntegerField()),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_estimated_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_actual_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Pending Review", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Paid", "Paid"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commission_weeks",
            },
        ),
        migrations.CreateModel(
            name="CommissionApplicationMapping",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estimated_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "commission_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.commissionweek",
                    ),
                ),
            ],
            options={
                "db_table": "commission_application_mappings",
            },
        ),
        migrations.AddField(
            model_name="commission",
            name="commission_week",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.commissionweek",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Cheque", "Cheque"),
                            ("Direct Debit", "Direct Debit"),
                            ("Standing Order", "Standing Order"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.application",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.insurancepolicy",
                    ),
                ),
                (
                    "mortgage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.mortgage",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "indexes": [
                    models.Index(
                        fields=["customer"], name="payments_custome_8fefc3_idx"
                    ),
                    models.Index(
                        fields=["application"], name="payments_applica_2d5ae8_idx"
                    ),
                    models.Index(
                        fields=["payment_status"], name="payments_payment_bbdde9_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_payment_aebcb7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="commissionweek",
            index=models.Index(
                fields=["advisor"], name="commission__advisor_5e5235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionweek",
            index=models.Index(
                fields=["week_number", "year"], name="commission__week_nu_d4dfa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionweek",
            index=models.Index(fields=["status"], name="commission__status_6f4478_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commissionweek",
            unique_together={("week_number", "year", "advisor")},
        ),
        migrations.AddIndex(
            model_name="commissionapplicationmapping",
            index=models.Index(
                fields=["application"], name="commission__applica_42eb6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionapplicationmapping",
            index=models.Index(
                fields=["commission_week"], name="commission__commiss_578ee7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commissionapplicationmapping",
            unique_together={("application", "commission_week")},
        ),
    ]
