# Generated by Django 5.2.5 on 2025-08-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_remove_document_file_path_document_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
