# Generated by Django 5.2.5 on 2025-08-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_application_postal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="postal_code",
        ),
    ]
