# Generated by Django 5.2.5 on 2025-09-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_remove_application_postal_code"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="commissiondispute",
            table="commission_dispute",
        ),
        migrations.AlterModelTable(
            name="commissionmapping",
            table="commission_mapping",
        ),
        migrations.AlterModelTable(
            name="commissionweek",
            table="commission_week",
        ),
        migrations.AlterModelTable(
            name="dailyadvisoractivity",
            table="daily_advisor_activity",
        ),
        migrations.AlterModelTable(
            name="policysaledetail",
            table="policy_sale_detail",
        ),
    ]
